create table alcohol_consumption(
country varchar2(50),
beer_servings number(10,5),
spirit_servings number(10,5),
wine_servings number(10,5),
total_litres_of_pure_alcohol number(10,5));


insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('afghanistan', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('albania', 89, 132, 54, 4.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('algeria', 25, 0, 14, 0.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('andorra', 245, 138, 312, 12.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('angola', 217, 57, 45, 5.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('antigua  barbuda', 102, 128, 45, 4.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('argentina', 193, 25, 221, 8.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('armenia', 21, 179, 11, 3.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('australia', 261, 72, 212, 10.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('austria', 279, 75, 191, 9.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('azerbaijan', 21, 46, 5, 1.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('bahamas', 122, 176, 51, 6.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('bahrain', 42, 63, 7, 2.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('bangladesh', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('barbados', 143, 173, 36, 6.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('belarus', 142, 373, 42, 14.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('belgium', 295, 84, 212, 10.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('belize', 263, 114, 8, 6.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('benin', 34, 4, 13, 1.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('bhutan', 23, 0, 0, 0.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('bolivia', 167, 41, 8, 3.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('bosnia-herzegovina', 76, 173, 8, 4.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('botswana', 173, 35, 35, 5.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('brazil', 245, 145, 16, 7.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('brunei', 31, 2, 1, 0.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('bulgaria', 231, 252, 94, 10.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('burkina faso', 25, 7, 7, 4.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('burundi', 88, 0, 0, 6.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('cote d**ivoire', 37, 1, 7, 4.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('cabo verde', 144, 56, 16, 4.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('cambodia', 57, 65, 1, 2.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('cameroon', 147, 1, 4, 5.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('canada', 240, 122, 100, 8.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('central african republic', 17, 2, 1, 1.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('chad', 15, 1, 1, 0.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('chile', 130, 124, 172, 7.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('china', 79, 192, 8, 5.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('colombia', 159, 76, 3, 4.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('comoros', 1, 3, 1, 0.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('congo', 76, 1, 9, 1.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('cook islands', 0, 254, 74, 5.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('costa rica', 149, 87, 11, 4.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('croatia', 230, 87, 254, 10.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('cuba', 93, 137, 5, 4.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('cyprus', 192, 154, 113, 8.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('czech republic', 361, 170, 134, 11.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('north korea', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('dr congo', 32, 3, 1, 2.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('denmark', 224, 81, 278, 10.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('djibouti', 15, 44, 3, 1.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('dominica', 52, 286, 26, 6.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('dominican republic', 193, 147, 9, 6.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('ecuador', 162, 74, 3, 4.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('egypt', 6, 4, 1, 0.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('el salvador', 52, 69, 2, 2.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('equatorial guinea', 92, 0, 233, 5.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('eritrea', 18, 0, 0, 0.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('estonia', 224, 194, 59, 9.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('ethiopia', 20, 3, 0, 0.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('fiji', 77, 35, 1, 2.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('finland', 263, 133, 97, 10.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('france', 127, 151, 370, 11.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('gabon', 347, 98, 59, 8.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('gambia', 8, 0, 1, 2.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('georgia', 52, 100, 149, 5.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('germany', 346, 117, 175, 11.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('ghana', 31, 3, 10, 1.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('greece', 133, 112, 218, 8.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('grenada', 199, 438, 28, 11.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('guatemala', 53, 69, 2, 2.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('guinea', 9, 0, 2, 0.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('guinea-bissau', 28, 31, 21, 2.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('guyana', 93, 302, 1, 7.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('haiti', 1, 326, 1, 5.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('honduras', 69, 98, 2, 3.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('hungary', 234, 215, 185, 11.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('iceland', 233, 61, 78, 6.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('india', 9, 114, 0, 2.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('indonesia', 5, 1, 0, 0.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('iran', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('iraq', 9, 3, 0, 0.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('ireland', 313, 118, 165, 11.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('israel', 63, 69, 9, 2.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('italy', 85, 42, 237, 6.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('jamaica', 82, 97, 9, 3.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('japan', 77, 202, 16, 7.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('jordan', 6, 21, 1, 0.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('kazakhstan', 124, 246, 12, 6.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('kenya', 58, 22, 2, 1.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('kiribati', 21, 34, 1, 1.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('kuwait', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('kyrgyzstan', 31, 97, 6, 2.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('laos', 62, 0, 123, 6.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('latvia', 281, 216, 62, 10.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('lebanon', 20, 55, 31, 1.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('lesotho', 82, 29, 0, 2.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('liberia', 19, 152, 2, 3.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('libya', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('lithuania', 343, 244, 56, 12.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('luxembourg', 236, 133, 271, 11.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('madagascar', 26, 15, 4, 0.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('malawi', 8, 11, 1, 1.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('malaysia', 13, 4, 0, 0.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('maldives', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('mali', 5, 1, 1, 0.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('malta', 149, 100, 120, 6.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('marshall islands', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('mauritania', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('mauritius', 98, 31, 18, 2.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('mexico', 238, 68, 5, 5.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('micronesia', 62, 50, 18, 2.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('monaco', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('mongolia', 77, 189, 8, 4.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('montenegro', 31, 114, 128, 4.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('morocco', 12, 6, 10, 0.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('mozambique', 47, 18, 5, 1.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('myanmar', 5, 1, 0, 0.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('namibia', 376, 3, 1, 6.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('nauru', 49, 0, 8, 1.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('nepal', 5, 6, 0, 0.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('netherlands', 251, 88, 190, 9.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('new zealand', 203, 79, 175, 9.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('nicaragua', 78, 118, 1, 3.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('niger', 3, 2, 1, 0.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('nigeria', 42, 5, 2, 9.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('niue', 188, 200, 7, 7.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('norway', 169, 71, 129, 6.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('oman', 22, 16, 1, 0.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('pakistan', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('palau', 306, 63, 23, 6.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('panama', 285, 104, 18, 7.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('papua new guinea', 44, 39, 1, 1.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('paraguay', 213, 117, 74, 7.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('peru', 163, 160, 21, 6.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('philippines', 71, 186, 1, 4.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('poland', 343, 215, 56, 10.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('portugal', 194, 67, 339, 11.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('qatar', 1, 42, 7, 0.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('south korea', 140, 16, 9, 9.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('moldova', 109, 226, 18, 6.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('romania', 297, 122, 167, 10.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('russian federation', 247, 326, 73, 11.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('rwanda', 43, 2, 0, 6.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('st. kitts  nevis', 194, 205, 32, 7.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('st. lucia', 171, 315, 71, 10.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('st. vincent  the grenadines', 120, 221, 11, 6.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('samoa', 105, 18, 24, 2.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('san marino', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('sao tome  principe', 56, 38, 140, 4.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('saudi arabia', 0, 5, 0, 0.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('senegal', 9, 1, 7, 0.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('serbia', 283, 131, 127, 9.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('seychelles', 157, 25, 51, 4.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('sierra leone', 25, 3, 2, 6.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('singapore', 60, 12, 11, 1.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('slovakia', 196, 293, 116, 11.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('slovenia', 270, 51, 276, 10.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('solomon islands', 56, 11, 1, 1.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('somalia', 0, 0, 0, 0.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('south africa', 225, 76, 81, 8.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('spain', 284, 157, 112, 10.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('sri lanka', 16, 104, 0, 2.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('sudan', 8, 13, 0, 1.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('suriname', 128, 178, 7, 5.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('swaziland', 90, 2, 2, 4.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('sweden', 152, 60, 186, 7.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('switzerland', 185, 100, 280, 10.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('syria', 5, 35, 16, 1.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('tajikistan', 2, 15, 0, 0.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('thailand', 99, 258, 1, 6.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('macedonia', 106, 27, 86, 3.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('timor-leste', 1, 1, 4, 0.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('togo', 36, 2, 19, 1.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('tonga', 36, 21, 5, 1.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('trinidad  tobago', 197, 156, 7, 6.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('tunisia', 51, 3, 20, 1.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('turkey', 51, 22, 7, 1.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('turkmenistan', 19, 71, 32, 2.2) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('tuvalu', 6, 41, 9, 1.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('uganda', 45, 9, 0, 8.3) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('ukraine', 206, 237, 45, 8.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('united arab emirates', 16, 135, 5, 2.8) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('united kingdom', 219, 126, 195, 10.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('tanzania', 36, 6, 1, 5.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('usa', 249, 158, 84, 8.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('uruguay', 115, 35, 220, 6.6) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('uzbekistan', 25, 101, 8, 2.4) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('vanuatu', 21, 18, 11, 0.9) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('venezuela', 333, 100, 3, 7.7) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('vietnam', 111, 2, 1, 2.0) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('yemen', 6, 0, 0, 0.1) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('zambia', 32, 19, 4, 2.5) ;
insert into alcohol_consumption(country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol) values ('zimbabwe', 64, 18, 4, 4.7) ;

select * from alcohol_consumption;



