select * from 테이블이름;

-- 내가 접속한 스키마의 테이블 이름 확인
select * from tab;

-- 만약 dba 권한이 있으면 모든 스키마의 테이블을 확인
select * from all_tables
where owner ='C##BIG';



-- 만약 dba 권한이 있으면 모든 테이블의 스키마 정보 확인
select * from ALL_TAB_COLS;

-- 테이블의 스키마 정보 조회
desc alcohol_consumption;

-- SELECTION 연습

SELECT * FROM ALCOHOL_CONSUMPTION;

SELECT SPIRIT_SERVINGS,WINE_SERVINGS FROM ALCOHOL_CONSUMPTION;


-- CONDITION
SELECT * FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS>45;

SELECT COUNTRY FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS>45;

SELECT SPIRIT_SERVINGS FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS>45;

--distinct
SELECT WINE_SERVINGS FROM ALCOHOL_CONSUMPTION;

SELECT DISTINCT WINE_SERVINGS FROM ALCOHOL_CONSUMPTION;

SELECT DISTINCT WINE_SERVINGS, SPIRIT_SERVINGS FROM ALCOHOL_CONSUMPTION;

SELECT ALL WINE_SERVINGS, SPIRIT_SERVINGS FROM ALCOHOL_CONSUMPTION;

-- 별칭설정
SELECT WINE_SERVINGS*1.1 AS WINE_VAT, BEER_SERVINGS*1.1 AS BEER_VAT
FROM ALCOHOL_CONSUMPTION;

-- ORDER BY
SELECT *
FROM ALCOHOL_CONSUMPTION
ORDER BY SPIRIT_SERVINGS, COUNTRY DESC;




