SELECT * FROM TAB;

SELECT * FROM ALCOHOL_CONSUMPTION;

SELECT COUNTRY, BEER_SERVINGS 
FROM ALCOHOL_CONSUMPTION;

SELECT WINE_SERVINGS
      ,COUNTRY
      ,BEER_SERVINGS 
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS <= 42;

SELECT WINE_SERVINGS
      ,BEER_SERVINGS
      ,COUNTRY
FROM ALCOHOL_CONSUMPTION 
ORDER BY WINE_SERVINGS;

SELECT WINE_SERVINGS,
       BEER_SERVINGS,
       COUNTRY
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS>51 AND BEER_SERVINGS>=35
ORDER BY WINE_SERVINGS DESC, BEER_SERVINGS DESC;

SELECT AVG(WINE_SERVINGS)
FROM ALCOHOL_CONSUMPTION;

SELECT '송현근',
       WINE_SERVINGS,
       WINE_SERVINGS+3,
       (SELECT AVG(WINE_SERVINGS) FROM ALCOHOL_CONSUMPTION)
FROM ALCOHOL_CONSUMPTION
WHERE COUNTRY = 'afghanistan';

SELECT COUNTRY,
       BEER_SERVINGS,
       WINE_SERVINGS,
      (SELECT AVG(WINE_SERVINGS) FROM ALCOHOL_CONSUMPTION)
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS>(SELECT AVG(WINE_SERVINGS) FROM ALCOHOL_CONSUMPTION)
ORDER BY WINE_SERVINGS ;

SELECT WINE_SERVINGS,
       BEER_SERVINGS,
       WINE_SERVINGS-BEER_SERVINGS
FROM ALCOHOL_CONSUMPTION;

SELECT COUNTRY,
       WINE_SERVINGS-BEER_SERVINGS AS DIFF,
       SPIRIT_SERVINGS
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS>BEER_SERVINGS;



-- WINE_SERVINGS가 BEER_SERVINGS의 값보다 5%이상 큰 행들 중 b로 시작하는 나라의 SPIRIT_SERVINGS를 기준으로 
-- 내림차순으로 COUNTRY와 TOTAL_LITRES_OF_PURE_ALCOHOL을 정렬하여 출력

SELECT COUNTRY,
       TOTAL_LITRES_OF_PURE_ALCOHOL
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS>BEER_SERVINGS*1.05 
      and country 
      like '%a%' 
ORDER BY SPIRIT_SERVINGS DESC
;


--LIKE 연산
SELECT COUNTRY
FROM ALCOHOL_CONSUMPTION
WHERE COUNTRY
      LIKE '%a%' 
AND COUNTRY 
    LIKE '%b%' ;

SELECT *
FROM ALCOHOL_CONSUMPTION
WHERE COUNTRY!='afghanistan';

SELECT *
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS=0;

SELECT *
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS IN(1,3,5,7,9);

--WINE_SERVINGS 0,1,3,5,7,9인 COLUMN을 가져와서 BEER_SERVINGS 가 10보다 크고 100보다 작은 모든 컬럼을 출력
SELECT *
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS IN(1,3,5,7,9)
      AND BEER_SERVINGS BETWEEN 10 AND 50;
      
--UPDATE

UPDATE ALCOHOL_CONSUMPTION
SET WINE_SERVINGS = '' WHERE COUNTRY='bhutan';

SELECT COUNTRY,WINE_SERVINGS 
FROM ALCOHOL_CONSUMPTION
WHERE COUNTRY='bhutan';

--UPDATE 각 COLUMN에서 값이 0인것은 전부 다 NULL ''로
UPDATE ALCOHOL_CONSUMPTION
SET WINE_SERVINGS='' WHERE WINE_SERVINGS=0;

--WINE_SERVINGS가 NULL인 값 찾기
SELECT *
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS IS NOT NULL;

-- WINE_SERVINGS 가 NULL이면서 BEER_SERVINGS 가 0인 COUNTRY 출력

SELECT COUNTRY
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS IS NULL
AND BEER_SERVINGS=0;


--ALCOHOL_WINE
--WINE_SERVINGS 가 NULL이 아닌 테이블
--ALCOHOL_BEER
--BEER_SERVINGS 가 0이 아닌 테이블

SELECT *
FROM ALCOHOL_CONSUMPTION
WHERE WINE_SERVINGS IS NOT NULL;

CREATE TABLE ALCOHOL_WINE 
AS (SELECT * FROM ALCOHOL_CONSUMPTION 
    WHERE WINE_SERVINGS 
    IS NOT NULL);

CREATE TABLE ALCOHOL_BEER 
AS (SELECT * FROM ALCOHOL_CONSUMPTION
    WHERE BEER_SERVINGS !=0);

-- 집합 연산자
SELECT *
FROM ALCOHOL_WINE
INTERSECT
SELECT *
FROM ALCOHOL_BEER;


-- 문자함수
SELECT UPPER(COUNTRY)
FROM ALCOHOL_CONSUMPTION;

SELECT *
FROM ALCOHOL_CONSUMPTION
WHERE COUNTRY like '%Korea%';

UPDATE ALCOHOL_CONSUMPTION
SET COUNTRY = INITCAP(COUNTRY);

COMMIT;

--우리나라의 BEER_SERVINGS와 WINE_SERVINGS의 차이를 구하면

SELECT BEER_SERVINGS-WINE_SERVINGS
FROM ALCOHOL_CONSUMPTION
WHERE UPPER(COUNTRY) LIKE UPPER('%Korea%')
AND LOWER(COUNTRY) LIKE LOWER('%SOUTH%');         --대문자인지 소문자인지 모를 때 전부 대문자OR 소문자로 변환하여 탐색

SELECT LENGTH(COUNTRY),COUNTRY
FROM ALCOHOL_CONSUMPTION;

SELECT COUNTRY
FROM ALCOHOL_CONSUMPTION
WHERE LENGTH(COUNTRY)>25;


SELECT a.*,
       a.WINE_SERVINGS+3
FROM ALCOHOL_CONSUMPTION a;



